---
# This playbook is running the unit tests for BIMS API

- hosts: all
  gather_facts: false
  vars:
  - slotname: "ut1"
  - bundle: "src/BCA/IntegrationBundle"
  - testSuite: "AppBundle,BusinessBundle,CoreBundle,IntegrationBundle,ModuleBundle,SalesforceBundle,AppBundle-Controller,DataBundle"
  - phpImage: "042475824269.dkr.ecr.eu-west-1.amazonaws.com/bims_api:{{ awx_workflow_job_name }}{{ awx_workflow_job_id }}"
  - redisHost: "redis-19834.c6.eu-west-1-1.ec2.cloud.redislabs.com"
  - redisPort: "19834"
  - redisPass: "Temporal01!"
  - imgPending: " is in progress![Pending](http://ps3trophies.com/forums/images/smilies/giggity.gif)"
  - imgOK: "![OK](https://cdn3.iconfinder.com/data/icons/fatcow/32/accept.png)"
  - imgKO: "![FAIL](https://nullthemedownload.com/content/logo/windows-error-lookup-tool-portable-logo.gif)"
  roles:
  - { role: bims.unittest_checkHost, when: checkHost is defined and checkHost}
  - { role: bims.unittest_run, when: execute is defined and execute}
  - { role: bims.unittest_processResults, when: processResults is defined and processResults }
