---
# This playbook is running the unit tests for BIMS API

- hosts: all
  vars:
  - slotname: "ut1"
  - bundle: "src/BCA/IntegrationBundle"
  - testSuite: "AppBundle,BusinessBundle,CoreBundle,IntegrationBundle,ModuleBundle,SalesforceBundle"
  roles:
  - { role: bims.unittest.checkHost, when: checkHost == "yes" }
  - { role: bims.unittest, when: execute == "yes" }
  - { role: bims.unittest.processResults, when: "phpunit_results is defined" }
