---
# This playbook is running the unit tests for BIMS API

- hosts: all
  vars:
  - slotname: "ut1"
  - bundle: "src/BCA/IntegrationBundle"
  - testSuite: "AppBundle,BusinessBundle,CoreBundle,IntegrationBundle,ModuleBundle,SalesforceBundle"
  roles:
  - bims.unittest
