---
# This playbook is running the unit tests for BIMS API

- hosts: all
  vars:
  - slotname: "ut1"
  - bundle: "src/BCA/IntegrationBundle"
  - testSuite: "AppBundle,BusinessBundle,CoreBundle,IntegrationBundle,ModuleBundle,SalesforceBundle"
  - phpImage: "042475824269.dkr.ecr.eu-west-1.amazonaws.com/bims_api:prtest"
  roles:
  - { role: bims.unittest_checkHost, when: checkHost is defined and checkHost}
  - { role: bims.unittest_run, when: execute is defined and execute}
  - { role: bims.unittest_processResults, when: processResults is defined and processResults }
